### ISSUE TITLE
goreleaser build fails

### ISSUE THREAD

**Issue by rimusz** [jfrog/kubenab#35]
```
   • BUILDING BINARIES        
      • building                  binary=dist/kubenab_windows_amd64/kubenab.exe
      • building                  binary=dist/kubenab_linux_amd64/kubenab
      • building                  binary=dist/kubenab_darwin_amd64/kubenab
   ⨯ release failed after 0.08s error=failed to build for windows_amd64: flag provided but not defined: -tags 'strip_debug'
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```

**Comment by l0nax** [comment]
This is because you have to switch into `cmd/kubenab`.

I do not know why this Error occurs but it seems like `goreleaser` only builds/ uses the `main.go` File.

**Comment by rimusz** [comment]
sorry, I put the old errors, updated my comment from the last build.

**Comment by l0nax** [comment]
Which commit do you have checked out?

Because I've tested it several times and it works: https://asciinema.org/a/PTVcJ2D6pIAJJqOBOk5HuRrVR

**Comment by rimusz** [comment]
https://github.com/jfrog/kubenab/releases/tag/0.3.4
Our release pipeline kicks in when the new tag gets added

**Comment by l0nax** [comment]
Add to the Pipeline to switch (temporary) into `cmd/kubenab` this will resolve the Error.

**Comment by l0nax** [comment]
> [...] it seems like goreleaser only builds/ uses the main.go File

And the `strip_debug` Flag is defined/ used only in the `log` Package.

**Comment by l0nax** [comment]
Does the Pipeline now work @rimusz?

**Comment by rimusz** [comment]
I haven't fixed it yet, too busy with other projects :)

**Comment by l0nax** [comment]
ok
