### ISSUE TITLE
Consider merging with jfrog/tugger

### ISSUE THREAD

**Issue by lhotrifork** [jfrog/kubenab#38]
**Is your feature request related to a problem? Please describe.**
What is the relationship of [jfrog/tugger](https://github.com/jfrog/tugger) and this project?
The README is nearly identical, but there is a great difference in the number of commits.

Should the two projects be merged, or alternatively one of them archived?

**Describe the solution you'd like**
Clarification of the relationship of the two projects, and ideally a merge of the two.

**Comment by rimusz** [comment]
it is based on jfrog/tugger and jfrog/tugger repo will be deleted

**Comment by l0nax** [comment]
With version 2 this project will have mutch more Configuration options and features.
But since I'm currently very busy at work, my PR have to wait for this project.
But internally in our Company, supporting and make future changes on this Project has a high priority because we heavily use it.

**Comment by rimusz** [comment]
jfrog/kubenab is the main project and is supported by JFrog and awesome contributor as @l0nax

**Comment by lhotrifork** [comment]
Thanks for the clarification, and your awesome work. 
I will add a disclaimer to the top of README.md in a PR explaining the relationship between the projects.
